spring:
  datasource:
#    url: jdbc:h2:./testDataBase;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;mode=MYSQL;NON_KEYWORDS=VALUE
    url: jdbc:h2:mem;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;mode=MYSQL;NON_KEYWORDS=VALUE
    username: sa
    password: sa

  h2.console:
    enabled: true
    path: '/console'



